### ISSUE TITLE
Partial Charges

### ISSUE THREAD

**Issue by arakelov-vahram** [hesther/espsim#30]
I would like to know if it is possible to calculate partial charges using your work flow?

**Comment by hesther** [comment]
Sure, you can calculate partial charges with the EspSim package using Psi4. If you just want partial charges and no similarity calculation, it would be easier to use psi4 directly, though. What exactly are you interested in? Happy to make an example if I can

**Comment by arakelov-vahram** [comment]
Thank you very much for your answer, Dr. Esther. I'm interested in calculating RESP charges using the HF/6-31G* basis set for a large dataset of around 100,000 molecules. Specifically, I'd like to extract the RESP charges for all the atoms involved and use this data as input features for my machine learning model.

I'm curious about how to validate the charges obtained from Psi4. I'm considering comparing my results with published research, particularly the work of Wendy D. Cornell and A. Kollman. What are your thoughts on this approach? I would greatly appreciate it if you could provide an example to help me better understand the process. Thank you!

**Comment by hesther** [comment]
Do you already have optimized geometries for your molecules? If not, I would suggest setting up a pipeline using psi4 only. If you do have optimized coordinates, there are some functions in the ESPsim package that might be helpful, that I can point you to. That being said, I think what you want is only Psi4 and Resp functionality, which is well documented online, including examples. 

Also, there is quite some literature on ML partial charges, maybe some of the existing models suit your needs? They also come with large datasets, eg https://doi.org/10.1039/D0SC04823B, or https://doi.org/10.1021/acs.jcim.7b00663

The level of theory is very low, are you sure about that choice? Do you want to develop a new ML model? Then I would go with a standard dataset from literature, else you have no comparison. Do the datasets not fit your usecases? Then you could extend them using an appropriate level of theory.
