### ISSUE TITLE
Origin of Pre-Computed Co-efficients

### ISSUE THREAD

**Issue by matthewtoholland** [hesther/espsim#31]
https://github.com/hesther/espsim/blob/da464267385810eae3115978e1cbb33ac9d8bae2/espsim/electrostatics.py#L180

Thank you for an excellent, and easy to use, package. I was wondering if you could shed some light on the origin of these co-efficients, and their significance?

**Comment by hesther** [comment]
@matthewtoholland Sure. We use 3 Gaussians to fit the Coulomb potential (i.e. the 1/R function in it). All the integrals then become a sum of two-center Gaussian integrals, for which an analytic solution is known (see the last equation on page 1 of https://pubs.acs.org/doi/abs/10.1021/ci00007a002). In this equation, we can precompute the prefactor and the factor in the exponent, since it only depends on the alphas of or Gaussian fit to 1/R, which again are known quantities taken from the same paper as above. Happy to send over equation if that helps

**Comment by hesther** [comment]
In a very old version, the Gaussian integral routine was not vectorized, it is more straightforward to understand it's direct relation to the above mentioned paper: https://github.com/hesther/espsim/pull/4/files

**Comment by matthewtoholland** [comment]
Thank you, this makes sense. Are you able to share the calculation you did to obtain them? I presume you are just fitting three Gaussians to a 1/r?

**Comment by hesther** [comment]
@matthewtoholland I don't have access to the original code anymore but I quickly wrote it anew using the equations and fit parameters from the above paper:

```
import numpy as np
alpha = np.array([0.0499,0.5026,0.0026])
gamma = np.array([0.3001,0.9716,0.1268])
print("precompute for a")
for i in range(3):
    for j in range(3):
        print(i,j,gamma[i]*gamma[j]*(np.pi/(alpha[i]+alpha[j]))**(3/2))
print("precompute for b")
for i in range(3):
    for j in range(3):
        print(i,j,-(alpha[i]*alpha[j])/(alpha[i]+alpha[j]))
```

which yields
```
precompute for a
0 0 15.906000360503185
0 1 3.9534831037285705
0 2 17.61453175624193
1 0 3.9534831037285705
1 1 5.215802058697395
1 2 1.9104538711424637
2 0 17.61453175624193
2 1 1.9104538711424637
2 2 238.75820252783515
precompute for b
0 0 -0.02495
0 1 -0.045393194570135756
0 2 -0.002471238095238095
1 0 -0.045393194570135756
1 1 -0.2513
1 2 -0.002586619160728424
2 0 -0.002471238095238095
2 1 -0.002586619160728424
2 2 -0.0013
```

Note that the code is ugly for readability here. And yes, the alpha and gamma parameters come from a simple fit to 1/r... which I took from the above paper (but you can obtain the same parameters by a least squares fit)

**Comment by matthewtoholland** [comment]
Thank you, very much appreciated!

**Comment by hesther** [comment]
You are welcome!
