### ISSUE TITLE
Psi4 error

### ISSUE THREAD

**Issue by PigUnderRoof** [hesther/espsim#6]
Hi, thank you for the great work.

I meed some problem when I try to run through the exaple notebook with partialCharges='resp'. The error is about key-values of options in helper.py. I try to modify it by removing the list in line 82. Then the charge output becomes only one value rather than a list/array in line 51 of electrostatics.py. I am not an expert of Psi4, hope these description can help you understand the issue.

Appreicate it if you can help, :D!

Best,

Chao

**Comment by PigUnderRoof** [comment]
I guess this issue arises because you assume the return value of resp.resp is a two layer tuple in line 82 of helper.py.

Maybe charge = resp.resp([mol], options)[1] can solve the issue?

**Comment by hesther** [comment]
Hi @PigUnderRoof , yes, I discovered the same problem last week, it seems like resp has changed what the resp() function returns. I will push an update soon to enable both versions, but currently you can safely use the change you proposed (`charge = resp.resp([mol], options)[1]`)

**Comment by hesther** [comment]
Seems like I had a very old version of resp in my conda environment, all newer versions are compatible with the change - so I just went ahead and pushed that change. Thanks for reporting!
